### ISSUE TITLE
Some valid imgur images refuse to load

### ISSUE THREAD

**Issue by bantar** [ccrama/Slide#1198]
Slide version: 4.7.3
Android version: 5.0

Certain images will not load.  The screen is darkened to highlight the picture, but the picture is blank (transparent).   If you click on the ... and Open Externally, it works just fine.  However, return to Slide, then try again and it still fails.    The image preview works fine, just not the image load.

I've seen this on numerous pictures, but wasn't able to capture the failure.   Here are two random ones that fail (its not easy to find these):
https://www.reddit.com/r/trees/comments/4adk7b/110_weed_man/
https://www.reddit.com/r/marvelstudios/comments/4af49k/my_local_theater_has_a_nice_photo_promoting_dr/

**Comment by ccrama** [comment]
Both of those load fine for me. Can you reproduce it again? If you can reproduce again it's an issue with the Imgur API or Slide, if it loads than it was just a network issue or the Imgur website was under heavy load at the time.

**Comment by bantar** [comment]
First, is there an easy way to go to these posts using Slide?  I have to start in /r/all and scroll down until I find these.   It's not easy for me to reproduce these.  

It's been over an hour since I've been on slide and I've just rechecked the Weed Man item.  It is consistently failing.    To find these failures, I've clicked on 100's of links to find those 2.   

Is it possible the it failed to load and cached a copy of the failure?    I don't know how to force a reload of the image other than clicking on it again.  

Right now, I'm trying to find the 2nd image again to retest it.

**Comment by bantar** [comment]
While scrolling and looking for the 2nd sample image to test, slide crashed.   When it resumed, I managed to find 2nd image and it's now working!   Consistently.   I went back and found the 1st image reported above (weed) and it's failing consistently.     At no point, did these failures feel like network failures.   Usually when I see network failures, I back out and reload the image and it corrects itself.   I don't know.   I suspected this might be somehow just related to me or my actions, but figured I should at least report it since I see it regularly.

**Comment by Alexendoo** [comment]
Lots of `03-15 17:18:19.569 26647-26731/me.ccrama.redditslide.debug W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (2368x4208, max=4096x4096)`

**Comment by ccrama** [comment]
That would explain why I don't get it and you guys do! What device are you on @bantar  and @Alexendoo ?

**Comment by Alexendoo** [comment]
Nexus 4, running 5.1.1 

Also [the second thread](https://www.reddit.com/r/marvelstudios/comments/4af49k/my_local_theater_has_a_nice_photo_promoting_dr/) doesn't do that for me, but it does cause a huge amount of lag - #1195 ?

**Comment by ccrama** [comment]
It's probably all related to images and rendering it on smaller screens. Once we figure out what size screen he has, we can narrow down the issue!

**Comment by Alexendoo** [comment]
Oh and @bantar for your question about an easy way to open the posts in slide, it'll open them directly if you click the link on your phone, or you can use pushbullet/join/etc to send the link to your phone if you're on another device

**Comment by bantar** [comment]
I'm using a Galaxy S5 with 2560x1440 resolution.

**Comment by bantar** [comment]
OK, I clicked on the links of these two sample failures and had them launch Slide.  I get an interesting different result.   The comments page loads up, but in both cases the preview image is blank.   When I clicked on these two images both loaded a blank image as well.

This is different from the original bug in that the preview image loaded just fine during the scrolling in the thread.  Then when I would click to get the comments, I would still see a valid preview image.  Now, I'm getting blanks for both the preview image and the full image.

**Comment by bantar** [comment]
In the other bug, I needed to reset the app data.  I also cleared the cache.  Then started slide, added my account and made no other settings changes.   I then launched both of these failing comment threads and see same result as reported just 6 minutes ago.   Both preview and full images are failing to load.

**Comment by bantar** [comment]
OK, I spoke too soon.   I put the phone down to type in my comment.   The phone timed out.   When I picked up the phone again and opened it, the preview picture for the theater  was properly loaded.  So, I clicked on the picture to see the big image.   It loaded blank.  However, I gave it a full 2 minutes to load before giving up.  I'm literally sitting 3 feet from the router and I'm on wifi.   Network speed is plentiful.

So, I tried the same set of steps with the weed post, but it continues to just load blanks.

**Comment by bantar** [comment]
I've found a few more failures in case this helps: 

Clearly, I should never be deprived of seeing this image:
https://www.reddit.com/r/FoodPorn/comments/4an5wu/loaded_fries_in_dublin_oc_4128_x_232/

https://www.reddit.com/r/comics/comments/4anime/gotta_reach_for_that_outrage/

And, BTW, my testing methodology for this error is to click on EVERY imgur link I find.   Since most work, I'd guess that there is a commonality amongst the samples that I'm finding (unless its strictly a failure on my device).

**Comment by Alexendoo** [comment]
The common point of failure should be high resolution images, in my case above 4096 in either dimension I presume it's similar on your end

**Comment by bantar** [comment]
Thanks.  I didn't look at the image sizes, however, since you mentioned it, let me recap what these 4 images sizes are:
 
1) Weed - 2,368px × 4,208px
2) Movie - 3,024px × 4,032px
3) Yummy Fries - 4,128px × 2,322px
4) Comic - 800px × 6,047px

Not quite the same for me as I'm seeing a failure at 4,032px.   However, this is the one and only one image that accidentally loaded once for me, but now continues to fail.

**Comment by bantar** [comment]
Well now that I know it's size...   Here is one more that fails:
https://www.reddit.com/r/The_Donald/comments/4aok24/trump_is_literally_hitler/
Trump - 800px × 6,047px

I did find a 4000px image over in /r/comics that worked just fine, so the 4K size might be the issue.  So, I'll not bother posting any more here.

**Comment by SZE2** [comment]
I'm having the same issue sporadically.

No crashing, just hanging.

Also, when this is the issue, the "open externally" button in the shadowbox does not work, I need to long-press the thumbnail.

 Here are the screencaps that show it clearly: www.vid.me/qa3n

**Comment by SZE2** [comment]
When I have it, it seems so stick u til I change networks or restart slide and clear cache.

Is there a way to send you logs without slide crashing?

**Comment by ccrama** [comment]
I think it may be fixed for v5 already, when I release the alpha let me know if it fixes your problems!

**Comment by ccrama** [comment]
I think I just fixed it for real this time. Feel free to re-open if you get the issue anymore

**Comment by SZE2** [comment]
Still getting it occasionally, turning in and off wifi will fix it though. When it happens, all Imgur content will not load, and Thumbnails will not load either.
