### ISSUE TITLE
ShadowBox - gfycat links play the gyf w/ a thumbnail on top it. m.imgur links only show a thumbnail

### ISSUE THREAD

**Issue by brentgsw** [ccrama/Slide#1238]
Slide version: 5
Android version:

Noticed a couple things w/ shadowbox. 
1. Gfycat links would play the gif, but would have a thumbnail over it , that if you clicked the thubmnail it would open another media player to play the gif unobstructed. 
2. m.imgur links only show a thumbnail, which you have to click and opens the link in a chrome tab.

**Comment by ccrama** [comment]
Thumbnail being a little world symbol?

**Comment by brentgsw** [comment]
correct.

**Comment by ccrama** [comment]
Has been fixed, thanks

**Comment by brentgsw** [comment]
@ccrama still having the gfycat link issue in shadowbox on the most recent build. Just built from source and still there.

**Comment by ccrama** [comment]
Has actually been fixed now
