### ISSUE TITLE
Toolbar keeps popping up after scrolling down after refresh of subreddit

### ISSUE THREAD

**Issue by pghant** [ccrama/Slide#1267]
Steps for reproduction:

1. In subreddit tab mode, load first subreddit.
2. Scroll down a few times.
3. Swipe over to next subreddit a few times.
4. Scroll subreddit tab bar over to first subreddit and reload it.
5. Your position is saved.
6. Tap subreddit name to go to the top.
7. Scroll down a few times. Notice that the toolbar keeps popping up each time.
8. The toolbar will stop popping up once you get past saved position.

Video of bug: https://vid.me/tj0Z

Slide version: 5.0.1
Android version: 6.0.1
Device: Nexus 6P

**Comment by Alexendoo** [comment]
Weird, good catch

**Comment by ccrama** [comment]
Believe this is now fixed!

**Comment by pghant** [comment]
I just updated to 5.3.3, and I'm still experiencing this issue. Also, I realized that this isn't limited to just the subreddit tab view. It happens whenever a subreddit is viewed again and the previous scroll state is saved.

Its definitely not a huge deal, just an annoyance for me since I switch between subreddits a lot, and I usually just keep Slide in RAM without closing it completely. Which means whenever I  reopen the app and refresh the subreddit, I experience this issue.

**Comment by ccrama** [comment]
Fixed for real this time!

**Comment by pghant** [comment]
Sorry, but I'm still experiencing this bug on v5.3.6.1.

**Comment by l3d00m** [comment]
I'm pretty sure the fix isn't pushed yet

**Comment by ccrama** [comment]
I fixed it 20 hours after doing 5.3.6.1
