### ISSUE TITLE
Disabling mail notifications causes a crash

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#129]
## Stacktrace
```java.lang.NullPointerException: Attempt to invoke virtual method 'void me.ccrama.redditslide.Notific
ations.Notific
ationJobScheduler.cancel(android.content.Context)' on a null object reference
at me.ccrama.redditslide.Activities.Settings$2$2.onCheckedChanged(Settings.java:103)
at android.widget.CompoundButton.setChecked(CompoundButton.java:154)
at android.widget.CompoundButton.toggle(CompoundButton.java:113)
at android.widget.CompoundButton.performClick(CompoundButton.java:118)
at android.view.View$PerformClick.run(View.java:19866)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.disp
atchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(N
ative Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)```
Reported via Slide Crash Capture

**Comment by ccrama** [comment]
Think this was fixed a while ago with 5422d6acc9e96c156e5b5e0048d8b385a2ab20c4

**Comment by Alexendoo** [comment]
Still occurs for me on the version after the recents menu fix

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void me.ccrama.redditslide.Notific
ations.Notific
ationJobScheduler.cancel(android.content.Context)' on a null object reference
at me.ccrama.redditslide.Activities.Inbox$1$2.onCheckedChanged(Inbox.java:109)
at android.widget.CompoundButton.setChecked(CompoundButton.java:154)
at android.widget.CompoundButton.toggle(CompoundButton.java:113)
at android.widget.CompoundButton.performClick(CompoundButton.java:118)
at android.view.View$PerformClick.run(View.java:19866)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.disp
atchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(N
ative Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by ccrama** [comment]
Fixed d04f085de21db2cd18d6b0b572f75ffb6862e75b
