### ISSUE TITLE
Sanitisation issues with the 'go to subreddit' input field

### ISSUE THREAD

**Issue by KaliK0t** [ccrama/Slide#143]
I cant type in underscores!

**Comment by karlding** [comment]
That's because of 824b092, which seems to have applied a filter on certain keys (including underscores) in an effort to sanitize the input... However, I'm not convinced that this is the best way to go about dealing with invalid input.

Is there any reason why the URI can't be encoded?

**Comment by ccrama** [comment]
@karlding what would be a better way to sanitize the input, in your opinion? Works beautifully for me, but everyone on Flesky is crashing :(

I COULD just sanitize it when they click to go, by removing everything that isn't a space or a number, but I think it looks better IMO if they just can't type it in the first place.

**Comment by karlding** [comment]
Why is it even necessary to go to such lengths to sanitize? I'm just getting started with Android development, but I feel like the way to go about this would be to allow any type of input, and then, afterwards:

1. Trim any trailing whitespace (since keyboards often add an extra space at the end)
2. Encode the trimmed string, treating it as an URI
3. Send the API request
4. If the resource doesn't exist, show an error page saying that the subreddit/profile/etc. doesn't exist

**Comment by ccrama** [comment]
It's pretty simple code, and if it can be fixed from the source instead of relying on a bad request, I'd rather go that route. That being said, I could do post-click sanitization (make sure it's characters or underscores), and that would probably work.

**Comment by ccrama** [comment]
Done 48b807297597f0174916f6fbb586ef2a21ecb1cc

**Comment by Alexendoo** [comment]
Still getting a crash when I type numbers in, however is this fixed by #171?
```
java.lang.IndexOutOfBoundsException: setSpan (0 ... 1) ends beyond length 0
at android.text.SpannableStringInternal.checkRange(SpannableStringInternal.java:351)
at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:79)
at android.text.SpannableString.setSpan(SpannableString.java:46)
at android.text.TextUtils.copySpansFrom(TextUtils.java:1036)
at me.ccrama.redditslide.SubredditInputFilter.filter(SubredditInputFilter.java:29)
at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:464)
at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:454)
at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:33)
at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:685)
at android.view.inputmethod.BaseInputConnection.setComposingText(BaseInputConnection.java:445)
at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:340)
at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
at android.os.Handler.disp
atchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(N
ative Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by ccrama** [comment]
Fixed with e5cbcea7f841b658d6b45480ffa4e6a77e36e3de

**Comment by Alexendoo** [comment]
Still crashes for me when typing any character not allowed by a subreddit
```
E/AndroidRuntime( 5972): FATAL EXCEPTION: main
E/AndroidRuntime( 5972): Process: me.ccrama.redditslide, PID: 5972
E/AndroidRuntime( 5972): java.lang.IndexOutOfBoundsException: setSpan (0 ... 1) ends beyond length 0
E/AndroidRuntime( 5972):        at android.text.SpannableStringInternal.checkRange(SpannableStringInternal.java:351)
E/AndroidRuntime( 5972):        at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:79)
E/AndroidRuntime( 5972):        at android.text.SpannableString.setSpan(SpannableString.java:46)
E/AndroidRuntime( 5972):        at android.text.TextUtils.copySpansFrom(TextUtils.java:1036)
E/AndroidRuntime( 5972):        at me.ccrama.redditslide.SubredditInputFilter.filter(SubredditInputFilter.java:29)
E/AndroidRuntime( 5972):        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:464)
E/AndroidRuntime( 5972):        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:454)
E/AndroidRuntime( 5972):        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:33)
E/AndroidRuntime( 5972):        at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:685)
E/AndroidRuntime( 5972):        at android.view.inputmethod.BaseInputConnection.setComposingText(BaseInputConnection.java:445)
E/AndroidRuntime( 5972):        at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:340)
E/AndroidRuntime( 5972):        at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
E/AndroidRuntime( 5972):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 5972):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 5972):        at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime( 5972):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5972):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 5972):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 5972):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by Alexendoo** [comment]
Also affects mutlireddit naming: 
```
E/AndroidRuntime( 7483): FATAL EXCEPTION: AsyncTask #2
E/AndroidRuntime( 7483): Process: me.ccrama.redditslide, PID: 7483
E/AndroidRuntime( 7483): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime( 7483):        at android.os.AsyncTask$3.done(AsyncTask.java:304)
E/AndroidRuntime( 7483):        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime( 7483):        at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime( 7483):        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime( 7483):        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/AndroidRuntime( 7483):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 7483):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 7483):        at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime( 7483): Caused by: java.lang.RuntimeException: Could not execute the request: HttpRequest {method='PUT', url=https://oauth.reddit.com/api/multi/user/alexendoo/m/Crash Time, expectedMediaType=application/json, headers=User-Agent: android:me.ccrama.RedditSlide:v4.0 (by /u/ccrama)
E/AndroidRuntime( 7483): Authorization: bearer ~~~~~Snip~~~~~~
E/AndroidRuntime( 7483): , body=net.dean.jraw.http.RequestBody$DefaultRequestBody@39280beb}
E/AndroidRuntime( 7483):        at net.dean.jraw.http.RestClient.execute(RestClient.java:144)
E/AndroidRuntime( 7483):        at net.dean.jraw.RedditClient.execute(RedditClient.java:147)
E/AndroidRuntime( 7483):        at net.dean.jraw.RedditClient.execute(RedditClient.java:141)
E/AndroidRuntime( 7483):        at net.dean.jraw.managers.MultiRedditManager.createOrUpdate(MultiRedditManager.java:73)
E/AndroidRuntime( 7483):        at me.ccrama.redditslide.Activities.CreateMulti$SaveMulti.doInBackground(CreateMulti.java:150)
E/AndroidRuntime( 7483):        at me.ccrama.redditslide.Activities.CreateMulti$SaveMulti.doInBackground(CreateMulti.java:145)
E/AndroidRuntime( 7483):        at android.os.AsyncTask$2.call(AsyncTask.java:292)
E/AndroidRuntime( 7483):        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime( 7483):        ... 4 more
E/AndroidRuntime( 7483): Caused by: java.io.IOException: Illegal character in path at index 57: https://oauth.reddit.com/api/multi/user/alexendoo/m/Crash Time
E/AndroidRuntime( 7483):        at com.squareup.okhttp.Request.uri(Request.java:66)
E/AndroidRuntime( 7483):        at com.squareup.okhttp.internal.http.HttpEngine.networkRequest(HttpEngine.java:643)
E/AndroidRuntime( 7483):        at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:218)
E/AndroidRuntime( 7483):        at com.squareup.okhttp.Call.getResponse(Call.java:271)
E/AndroidRuntime( 7483):        at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
E/AndroidRuntime( 7483):        at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
E/AndroidRuntime( 7483):        at com.squareup.okhttp.Call.execute(Call.java:79)
E/AndroidRuntime( 7483):        at net.dean.jraw.http.OkHttpAdapter.execute(OkHttpAdapter.java:64)
E/AndroidRuntime( 7483):        at net.dean.jraw.http.RestClient.execute(RestClient.java:120)
E/AndroidRuntime( 7483):        ... 11 more
```

**Comment by ccrama** [comment]
Does it not give you an error when you try to create it? Does the multi show up on reddit.com?

**Comment by KaliK0t** [comment]
No error. Just slide has stopped. And it doesnt show up anywhere

**Comment by ccrama** [comment]
That honestly sounds like a Reddit bug :(

**Comment by Alexendoo** [comment]
The names can't have spaces in them, I caused the crash by attempting to create one called 'Crash Time'

**Comment by Alexendoo** [comment]
These all seem like percent encoding would help tonnes, since a space should never really appear in a URL

**Comment by ccrama** [comment]
Final bug with multis fixed with 83b7611

**Comment by Alexendoo** [comment]
Still crashes when any character not allowed is typed in

**Comment by l3d00m** [comment]
Profile and multireddit input fields are sanitised now.
