### ISSUE TITLE
Slide Video Plugin orientation issue

### ISSUE THREAD

**Issue by ArthurHeng** [ccrama/Slide#1552]
Slide version:5.3.2.4
Android version:5.0

In fullscreen mode, if I change the way I HOLD my phone, example from landscape to portrait, the video plugin will quit fullscreen mode. I made sure the Auto Rotate option on my phone is off.

Steps to reproduce:
1)Set Android auto rotation to off.
2)Play a youtube video in Slide.
3)Make it fullscreen by pressing button on bottom right, hold phone in landscape orientation.
4)While video is playing in fullscreen landscape, hold phone in portrait orientation.

Video playback should revert back to portrait and non fullscreen.

I tried to capture a video but AZ Screen Recorder is dumb as it does not obey my screen orientation settings either, despite already set, therefore the video I capture will further confuse you. If you guys really want to see a video kindly recommend a free+non-root screen capture app.

**Comment by ccrama** [comment]
That's a limitation with Google's YouTube library, unfortunately. Don't really have a fix right now

**Comment by ccrama** [comment]
Fixed, actually. Thanks for the report!

**Comment by ArthurHeng** [comment]
Ccrama, thanks but I tried the latest video plugin the issue persists.

**Comment by ccrama** [comment]
Oh, what you're in is immersive mode. Click the bottom button to exit immersive and you can change orientation

**Comment by ArthurHeng** [comment]
Click which bottom button?

**Comment by ccrama** [comment]
The same one you clicked to enter fullscreen mode

**Comment by ArthurHeng** [comment]
Actually the issue is that it changes orientation when it is not supposed to.
