### ISSUE TITLE
App frequently does not load any content until restart

### ISSUE THREAD

**Issue by unsourced** [ccrama/Slide#1594]
Slide version: 5.3
Android version: 6.0

Frequently, after a bit of use (basically every time I use the app for more than a few minutes), I find that nothing will load. This includes comments and posts. The loading spinner just spins and spins. If I try to enter a subreddit that isn't saved to my sidebar I get: "Subreddit not found: The subreddit ___ could not be found. Perhaps it's spelled wrong, or you do not have access to this subreddit." If it is a saved sub then only the sub's action bar loads, as well as most of the sidebar, but no posts or comments.

As a note, I am using the app in guest mode. I thought perhaps the problem was with some of my user data, so I uninstalled the Play store app and reinstalled from Fdroid. Same problem, it is making this app almost unusable, which is a shame, because it's a very impressive app. This issue is not specific to 5.3, as I have had the same problem over a number of versions at this point. I can't even fix the problem by backing out and using the confirm dialog to exit. I have to go into my recents menu, swipe the app away and open it again, this works every time to get it loading pages again, but it is quite disruptive.

**Comment by Nxt3** [comment]
I can vouch for this behavior. I couldn't tell you how to reproduce it though--it just happens sometimes.

**Comment by ccrama** [comment]
Haven't run into this before. In the past if this happens, restarting WiFi fixed it for me because it was an internet connectivity issue and not a Slide issue

**Comment by ccrama** [comment]
Actually guest mode doesn't ever try to re-authenticate so it's a bug with Guest mode. Has been fixed!

**Comment by unsourced** [comment]
First of all, thanks for dealing with this so quickly. Unfortunately, I have updated to 5.3.4 and the problem is still present. I think it might be happening less frequently, but as the problem was temperamental to begin with, I don't have any way of knowing for sure. Is it possible to reopen this issue?

To reiterate, (in guest mode) I am still getting the same fairly frequent problem where the app will not load comments, posts, or unsaved subs (same "Subreddit not found") message. The only way to fix the problem is to either swipe away the app from recents or to use the sliding menu options "go offline" and then "try to enter online mode". Since these solutions have worked every time I have tried them so far, it seems to suggest a consistent problem. I have tried restarting WIFI (and also mobile data) but it is has not fixed the problem.

One other thing I have noticed, which might help pinpoint the problem, is that this tends to happen more often when I leave the app and come back again. This is particularly the case with phone calls. If I get a call and resume the app then almost every time it needs to be reset in order to load any content. However, phone calls are not the only condition which cause this problem, just one that appears to cause it more consistently.

**Comment by ccrama** [comment]
@unsourced  somehow my commit got reversed and the code is gone. Have re-fixed it for the next update!

**Comment by unsourced** [comment]
Wow, you are quick! Thanks, again. Hopefully, this will be my last comment on this issue.

**Comment by unsourced** [comment]
I have updated to 5.3.6 and unfortunately the problem is still present, as described above.

**Comment by ccrama** [comment]
I have gotten many reports that it is fixed, so what exactly are the steps to reproduce?

**Comment by unsourced** [comment]
I have been trying to test this to figure out exactly what triggers this, and I still have no idea. All I know is how to fix the problem consistently, which is always the same steps. Unfortunately, the problem is still occurring fairly regularly, and it gives me the same "subreddit not found", "user not found" error messages, and will not load content until a swipe away restart or offline mode toggle within the app.

As for creating the problem, I find that switching to other apps for a while and returning to it, or going from Slide to a longer phone call and then back again seem to cause this issue more frequently, although, they don't always cause it, and they are not the only causes. Performing these actions seem to cause the bug more consistently, although, after enough use the app will always give me this problem.

**Comment by ccrama** [comment]
The only thing that would cause it not to re-authenticate is if Slide detects no internet connection, which would probably explain all your issues. What device are you on?

**Comment by unsourced** [comment]
HTC One M8 on Android 6.0. HTC Sense 7.0

It wouldn't surprise me if this was related to a connection issue, since toggling offline seems work every time. However, if that is the case, it means that Slide isn't detecting a connection even after it is has been reestablished. (None of my other apps seem to be doing anything like this with the internet, besides the occasional hanging in Chrome.) If I switch to any other app, the internet seems to work fine, and simply restarting the connection always gets Slide working again.

**Comment by ccrama** [comment]
Well slide checks your internet access apart from trying to load content. Other apps take a load first and detect issues later, but because Slide has a lot of offline capabilities, I check for offline first and make sure I won't run into issues. What network do you use typically?

**Comment by unsourced** [comment]
I have mostly been on WiFi when using the app, although, I do get the problem on mobile data as well. Overall the connection is pretty strong, but it very well may dip from time to time.

I am not sure what is going on in the back end, but is there any way the app can recheck the connection if there are loading problems in online mode? Maybe a prompt like "You are having difficulty reaching the network would you like to try again or go offline?" With two options: "try again" [does another check (and re-authenticates?)] "go offline".  I know this has kind of morphed into a feature request, but it is causing basic usability problems so perhaps this is a roundabout way of getting to a solution. Or is there another way to reconnect the app without disturbing offline mode?

**Comment by ccrama** [comment]
Appears it may have been a bug with the library I was using to access Reddit, will hopefully be fixed before the next version

**Comment by unsourced** [comment]
Was this library bug fixed?

I am on version 5.5 and, unfortunately, I am still getting this problem.
