### ISSUE TITLE
Domain subscriptions don't work/load with the widget

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1710]
Slide version: 5.3.6-alpha.3
Android version: 6.0.1

**Comment by ccrama** [comment]
Fixed!

**Comment by Controless** [comment]
@ccrama Huh weird, it still doesn't seem to work for me. It is working for you?

**Comment by ccrama** [comment]
Yeah, how are you adding it?

**Comment by Controless** [comment]
I'm just adding it normally using nova launcher. Long pressing home screen, clicking widgets, and dragging the slide widget. Weird that it's not working for me.

**Comment by ccrama** [comment]
Does the title have a dot in it?

**Comment by Controless** [comment]
Oh, it doesn't have a dot in it. It's just githubcom, but I added "github.com" as the domain name though. Any idea why it's not displaying the .?

**Comment by ccrama** [comment]
Ah, gotcha. Have fixed!

**Comment by Controless** [comment]
Thanks! :)
