### ISSUE TITLE
Navigation drawer subreddit filter text box lowers/unfocuses keyboard after entering 1 character in landscape

### ISSUE THREAD

**Issue by RB-NT** [ccrama/Slide#2147]
Slide version: 5.4.3
Android version: Android 7.0 Nougat

It also doesn't raise the keyboard when the box is re-tapped.
Video: https://www.youtube.com/watch?v=y6JY7FllcOI

**Comment by ccrama** [comment]
Thanks for the report, has been fixed!

**Comment by RB-NT** [comment]
I am on the latest update (5.4.3.5) and I am still experiencing this issue.

**Comment by ccrama** [comment]
I cannot reproduce anymore

**Comment by RB-NT** [comment]
I'm going to clear the app data real quick and see if it still happens.

**Comment by RB-NT** [comment]
It still occurs. I am using the latest English Google keyboard.

**Comment by ccrama** [comment]
None of that code changed in the last 2 updates, so the update is likely
not the reason it changed

**Comment by RB-NT** [comment]
I'm a noob with github, I only have spent a few hours learning it, so please forgive me. But are you saying that the commit you made to fix this issue isn't in 5.4.3.5 yet?

**Comment by ccrama** [comment]
Sorry for the confusion. I fixed it for v5.4.3 and nothing has changed in
5.4.3.1 and 5.4.3.5

**Comment by RB-NT** [comment]
So the issue won't be fixed until the next significant version? (5.4.4?)
If so, then sorry for bugging you. I'm not familiar with how long it normally takes to get out to the app store.

**Comment by ccrama** [comment]
No, meant it has been fixed for 3 days in production (and many users have
told me it was fixed)

**Comment by RB-NT** [comment]
Okay. I believe I understand now. Thanks for your time and dedication to this app.

**Comment by ccrama** [comment]
No worries! What version of Android are you on?

**Comment by RB-NT** [comment]
7.0
