### ISSUE TITLE
Peeking no longer marks the post as read

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#2267]

**Comment by ccrama** [comment]
Should be fixed now, thanks for the find! I actually don't think I ever implemented it to begin with

**Comment by Nxt3** [comment]
I swear it was doing this at one point. Whatever fix you've done still doesn't seem to work for me.

**Comment by ccrama** [comment]
It actually worked, just didn't color the titles. Fixed!
