### ISSUE TITLE
Links with ampersands are HTML-escaped when copied from certain buttons

### ISSUE THREAD

**Issue by BytewaveMLP** [ccrama/Slide#2328]
**Slide version:** 5.5.3
**Android version:** 6.0.1

When long-pressing on link previews in both subreddit and post views and choosing the "Copy URL" option from the three-button menu that pops up ([example](https://ul42l.xyz/viewfile/3/Screenshot_20161217-122042.png)), I've noticed that all ampersands (`&`) are converted into their HTML entity representation (`&amp;`). This is especially noticeable on reddituploads links, which require GET parameters on the URL. This doesn't happen when using the "Share Link" option from the 3-dot menu on posts or long-pressing the post card itself.

**Comment by ccrama** [comment]
Should be fixed now, thanks for the report!

**Comment by BytewaveMLP** [comment]
I'm still seeing this issue on 5.5.4 from the Play Store, unless that isn't the version containing this fix. Though, the update went a little strange; had to tell it to update two or so times before it would finish.

**Comment by BytewaveMLP** [comment]
Using [this post](https://reddit.com/r/test/comments/5ivqtd/testing_something_for_slide_for_reddit_bug_report/) to test, if it's important somehow.

**Comment by yaomtc** [comment]
This is happening with the latest version on F-Droid (5.5.4), here's the link I saw it on: https://www.reddit.com/r/ElderScrolls/comments/65chu4/bad_apple/

**Comment by ccrama** [comment]
The latest version is 5.5.5 (not 5.5.4), it was fixed in 5.5.5

**Comment by yaomtc** [comment]
Huh, that's odd... The F-Droid app installed the previous version for some reason, and doesn't give me an Update button though it does show the newer version above it. 5.5.4 also has a star by it, but I don't know what that means.

Well, I updated, cleared the app from memory and opened it, and it's still happening: https://imgur.com/a/oeMvp

**Comment by ccrama** [comment]
If you actually share it, does it have the ampersand? The title of that
menu is not what gets shared

**Comment by yaomtc** [comment]
If I open the link in the built in browser, it goes to the main page because of the &amp;. If I press Copy URL, the &amp; is in the URL. Sharing is the only thing that works properly.

**Comment by yaomtc** [comment]
Replace the ampersands in the last comment with &-amp-semicolons. \&amp; ?

**Comment by BytewaveMLP** [comment]
Can confirm that this issue is still present in latest Play Store beta release 5.5.7. It does **not** occur when holding down the post card and pressing "Share Link" (using Android's default Copy to Clipboard activity), but it **does** occur when holding the **link preview** and pressing **Copy URL**, as well as holding on the link preview in the comments view and pressing **Copy URL**.

In essence, anything that passes it straight to Android's share menu works fine. But anything that directly writes to the clipboard writes `&amp;`.

**Comment by moshpirit** [comment]
[Also happens with flairs](http://i.imgur.com/xiEGWGb.png)

**Comment by BytewaveMLP** [comment]
This also appears to affect opening the link in an external browser, from what I've noticed.
