### ISSUE TITLE
Gfycat issues with IPv6

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#2395]
If I have IPv6 enabled on my router, Gfycat links won't load in Slide (they load fine in Chrome and on my desktop).

[This is a known issue with Gfycat; however, the Reddit is Fun dev posted a workaround for this issue here](https://www.reddit.com/r/gfycat/comments/5y2dkm/psa_for_android_devs_how_to_work_around_ipv6/)

Is this possible to fix in Slide?

**Comment by ccrama** [comment]
Done! Thanks for finding that!

**Comment by Nxt3** [comment]
So this is still an issue. I just got Google Fiber and have IPv6 addresses and can't see Gfycat gifs in Slide. :/

**Comment by ccrama** [comment]
I feel like this would be much more reported if the issue was widespread (nothing on the subreddit since that change), is there any way to isolate and see if your settings/device could be the issue?

**Comment by Nxt3** [comment]
@ccrama 2XL, yeah.

**Comment by ccrama** [comment]
Do you have an example link that is not working?

**Comment by Nxt3** [comment]
It's every single Gfycat link.

**Comment by ccrama** [comment]
Would you be able to debug this one? I can't reproduce so not much I can to to help :(

**Comment by Nxt3** [comment]
Now I can't reproduce it either. Weird. I'll keep an eye out. Sorry about that.

**Comment by ratorx** [comment]
I'm also having this issue. [Example Link](https://gfycat.com/ShyGranularFrillneckedlizard)
Slide v5.8.7
Android version 8.1

**Comment by levinuss** [comment]
I also experience this issue for some time now. I have IPv6 enabled in my home network and can also reach Gyfcat via v6, in the Browser the website loads fine. If I try to load gyfcat from Slide it just does not load somehow. When I disconnect from my home network and use the mobile network it works. Could this the issue described in OP? Is there a fix/workaround  other than turning v6 off?
