### ISSUE TITLE
SytemUI crashes when downloading hi-res image

### ISSUE THREAD

**Issue by ImjuzCY** [ccrama/Slide#2506]
Slide version: v5.6.3
Android version: 7.1.2

I'm on LineageOS, and I found that SystemUI crashes when I download very high resolution images (for example a 8000x6000 from r/EarthPorn). I suspect that it's the notification when the download is done, it shows the full resolution of the image, causing SystemUI to run out of memory. Other than crashes, my notification page also lags severely when I download images not that large (for example a 4000x3000 image). I would suggest that either use a scaled down version to be shown in the notification or not showing the image at all so that this would not be affecting user experience.

I think this issue should be categorised as high priority?

**Comment by matty1086** [comment]
Can confirm the System UI crashing aspect. Same thing happens to me with the following:

Slide version: v5.6.5.1-alpha4
Android version: 8.0 Final (Nexus 6P)

This put me into a System UI crashing loop that was only fixed by rebooting the device.

**Comment by ImjuzCY** [comment]
Solved in v5.6.5-alpha6

**Comment by ImjuzCY** [comment]
Still happening on v5.8-alpha1.5

**Comment by Tensounder54** [comment]
Can conferm that this is still an issue in Slide version 5.9-alpha2. I'm not sure what we can do to solve this as I think that its a Reddit thing in terms of packet size.
