### ISSUE TITLE
Low quality preview on certain gifs

### ISSUE THREAD

**Issue by anonymous-user** [ccrama/Slide#2517]
Slide version: 5.6.5.1-alpha4
Android version: 7.1.2 (Dirty Unicorns 11.6 custom ROM)

So far the two examples I would were hosting on Imgur but it doesn't seem to happen with all gifs hosted on Imgur. I would need to do more testing to narrow down a possible culprit though I want to say it may be the particular link format chosen. Also I am on wifi and do not have data saving enabled. Also when I viewing the previews, it in the subreddit view with big picture enabled.

Warning! **NSFW**:

https://www.reddit.com/r/hentai/comments/6tyii6/lending_her_a_hand_futa/

https://www.reddit.com/r/hentai/comments/6u7d5b/reverse_cowgirls_gif/

**Comment by ccrama** [comment]
Could you repeat the test with alpha 4 number 2? Should be version number 280. I believe this issue should be fixed

**Comment by anonymous-user** [comment]
How do I tell I'm on Alpha 4 number 2? I don't see where to check the version number 280. Anyways Slide is up-to-date according to the Play Store and I still have the issue.

**Comment by ccrama** [comment]
All I do for imgur gifs is add .mp4 after the imgur hash. Are you sure data saving is not enabled on your device?

**Comment by anonymous-user** [comment]
I am positive. I also tried clearing Slide's data and cache and re-logged in. Without modifying any settings (except the theme color and to view NSFW content) I went into the saved section and checked the thumbnails, they are still bad quality.

NSFW: http://imgur.com/a/Ca250

**Comment by ccrama** [comment]
Should be better now in the next alpha! If it does not fix your issue, feel free to re-open this issue

**Comment by anonymous-user** [comment]
Sadly not fixed for me.

**Comment by ccrama** [comment]
Oh I was mistaken, I thought you meant the gifs were low quality. Sadly, I display exactly what Reddit gives to me as the preview, and the graininess is an issue on their end. They have talked about possibly improving this in the future, but for now we can only wait

**Comment by anonymous-user** [comment]
I tried viewing the problem posts in Sync for reddit but it doesn't have the problem. I see a big difference in their previews though. Slide seems to be showing a cropped and/or zoomed in picture whereas Sync shows the whole image. I thought this may be related to Slide's "Crop lead image in comment view" but disabling it doesn't fix the quality.

Warning! NFSW!

Slide: https://i.imgur.com/gcFP3ci.jpg

Sync: https://i.imgur.com/zgYwXCt.jpg

**Comment by ccrama** [comment]
That is because Sync has its own server and does processing there, which we don't have the luxury of using

**Comment by anonymous-user** [comment]
So other Reddit clients should show similarly bad quality provided they don't use their own servers?

Also why are only some image previews bad?

**Comment by anonymous-user** [comment]
BTW I just tried Reddit is fun and Boost for Reddit. Neither has the low quality previews.

**Comment by ccrama** [comment]
They aren't displaying the Reddit-provided preview, you can view it for yourself if you visit https://www.reddit.com/r/hentai/comments/6tyii6/lending_her_a_hand_futa/.json and view the media preview image. It's quite low quality. It is showing the Reddit preview instead of displaying the Imgur image itself, which is why you're seeing different results

**Comment by anonymous-user** [comment]
I'm guessing the benefit of showing the preview is a smaller size? Would it possible to show the entire image just scaled down? Even if it has to be an optional setting.

**Comment by ccrama** [comment]
It's for consistency, and some imgur images are gifs not images, which would cause issues and require url checking at the post fetching level instead of the media view level (like .gifs linked as .png)

**Comment by anonymous-user** [comment]
Ok well thanks for explaining this to me.
