### ISSUE TITLE
Saved section doesn't load

### ISSUE THREAD

**Issue by bpclarke** [ccrama/Slide#2580]
Slide version: 5.7.1 but this has persisted for at least a year & I update regularly
Android version: 7.0

This has persisted across multiple phones. Nexus 5 and now Galaxy S7.

When I go on my saved section nothing loads unless I have only just saved it. I am logged into my reddit account

**Comment by Tensounder54** [comment]
This issue is resolved in a later version of Slide and needs to be closed.

**Comment by bpclarke** [comment]
Still got the bug on Slide version 5.8.7 (latest version)

**Comment by Tensounder54** [comment]
@bpclarke That's not the latest version of Slide. The latest version is 5.9-alpha2. This issue has been resolved in that version and so it can be closed.

**Comment by bpclarke** [comment]
@Tensounder54 ok I signed up to the beta program and downloaded 5.9-alpha2 and I still have the bug. Tried logging out and in again and also uninstalling & reinstalling the app.

**Comment by Tensounder54** [comment]
This issue is resolved in a later version of Slide and as such I'm going to close it.
