### ISSUE TITLE
Issues with image saving

### ISSUE THREAD

**Issue by Pacogens** [ccrama/Slide#260]
When I try to save an image, mostly times it doesn't work, other times the app shows that error.

And, please, make the option to choose what format want to save a gif, mp4 or .gif. Like imgur app.

😇😇😇

**Comment by ccrama** [comment]
Fixed a while ago I think. And that might be a future improvement to add, but not for the next release :s

**Comment by okungnyo** [comment]
I can confirm saving still doesn't work. Pics and GIF/GIFV/Gfycat/etc. both do not save.

**Comment by l3d00m** [comment]
still not saving @okungnyo @Pacogens ? I have no problems any longer.

**Comment by okungnyo** [comment]
Running Slide v4.3.4 on Android 6.0. Still not working.

When I click the floppy icon, I get a "Uh oh, something went wrong! Would you like to try again? [NO] [YES]"

I thought the problem was that even though Slide targets Marshmallow, it doesn't ask for Storage permissions when I try to save a pic.

So I went to Settings>Apps and manually gave Slide the permission.

Still doesn't work, and I get the same "Uh oh, something went wrong! Would you like to try again? [NO] [YES]" message.

**Comment by l3d00m** [comment]
The image saving is reworked now, so it should work now.
