### ISSUE TITLE
Videos won't load, causes nothing else to load

### ISSUE THREAD

**Issue by selketdaly** [ccrama/Slide#2744]
Slide version: 5.8.6
Android version: 7.0

When loading a Reddit video (v.redd.it), video will load incredibly slowly, both o  data and Wi-Fi. Often it will get stuck loading.

If it gets stuck loading, comments and new posts won't get loading by the app and appear to hang.

**Comment by Tensounder54** [comment]
This issue is resolved in a later version of Slide and needs to be closed.

**Comment by selketdaly** [comment]
I am now on Slide 5.8.7 and this is still an issue. Which version will it be resolved in?

**Comment by Tensounder54** [comment]
It's resolved in Slide Version 5.9-alpha2 although it is still on the slow side but I'm not sure there is much we can do about that as we have to download the videos from the Reddit server and then load them into slide which does take some time. It doesn't normally take longer than 10s though.
