### ISSUE TITLE
Bad performance on really long threads

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#2791]
Slide 5.8.6

LineageOS 14.1

Moto X Pure

This might be due to my aging phone, but really long threads cause lag when performing any action but scrolling. Scrolling is still smooth, but when you go to upvote or downvote the animation chops and takes a couple seconds before the tap registers.

This only happens when you're really far down in the thread.

This has been happening for as long as I can remember, even back to the earlier days. It might not even be fixable.

**Comment by Nxt3** [comment]
Yeah this has been a thing since forever. Even on my Pixel 2XL

**Comment by alexsmithfanning** [comment]
@ccrama I sent you a report via the "send feedback" button because the lag got so bad that it eventually froze.

**Comment by alexsmithfanning** [comment]
@Nxt3 good to know it's not just that my phone is getting old.

**Comment by ccrama** [comment]
@Nxt3 I've never experienced this on many devices, is it possibly a setting you and @alexsmithfanning have enabled in Settings > Comments?

**Comment by alexsmithfanning** [comment]
@ccrama try [this thread](https://www.reddit.com/r/AskReddit/comments/8lj4fn/what_small_thing_should_be_illegal_because_it/) and keep loading more commends. It should start to get laggy and eventually cripple itself.

**Comment by ccrama** [comment]
@alexsmithfanning I loaded 10k more and have no lag opening menus or voting, even on the bottom comments. Mind posting your comment settings screen?

**Comment by Nxt3** [comment]
Here are my comment settings

![](https://i.imgur.com/dVoFVL8.png)

![](https://i.imgur.com/BkrBHSe.png)

**Comment by ccrama** [comment]
Ah, the issue is fully collapse comments, that allows hundreds more views to stay on the screen at a time, pushing the limits of the RecyclerView and how we do comments. Unsure if there is a way to remedy that

**Comment by PiwwowPants** [comment]
Even with child comments expanded by default I made it 10k down plus the children and everything was fine on my end. Assuming this is a RecyclerView that makes sense and shouldn't hit this issue naturally. I'll try to copy settings exactly and see.

**Comment by alexsmithfanning** [comment]
Hmm. I'm not noticing it after Slide crashed and I had to restart it. I'm thinking it has to be open for a while, and multiple long threads have to be view and exited before the issue appears. I'll keep experimenting.

**Comment by PiwwowPants** [comment]
Sounds good. With @nxt3 exact settings, at a bit after 10k I saw some minor lag only when scrolling very fast. Nearing 13k (I think) it was noticeably not animating when scrolling very fast but in a normal speed where you're not flinging everything was still fine. 

Scrolling all the way back up again with a finger on the fingerprint scanner still didn't show an issue. So maybe it is conditional from length of time open (?)

**Comment by alexsmithfanning** [comment]
I had to browse the thread, upvote multiple posts, load a lot of sub-comments, and get pretty far down in the post, then I noticed quite a bit of animation lag when going to upvote something.

**Comment by alexsmithfanning** [comment]
After letting it sit in the background it got very noticably worse when I returned.

**Comment by ccrama** [comment]
I am not able to reproduce on a Pixel XL or Galaxy S9+. Would it be possible for you to make a backup of slide to file *without personal info* and post it somewhere I can download it from? Even pastebin would work

**Comment by alexsmithfanning** [comment]
Do you mean backup the app?

**Comment by ccrama** [comment]
Yes you can backup to file

**Comment by alexsmithfanning** [comment]
I'll do it after I get off work.

**Comment by alexsmithfanning** [comment]
@ccrama How do I do a backup without personal info?

**Comment by ccrama** [comment]
It gives you the option when you click backup

**Comment by alexsmithfanning** [comment]
@ccrama Sorry now I feel like an idiot.

[Here's my settings.](https://pastebin.com/XRySaUTt)

**Comment by azumukupoe** [comment]
Same

**Comment by Nxt3** [comment]
@ccrama For me, it's mostly opening and closing the comment menu you see choppiness. Lemme record an example, hold on.

**Comment by Nxt3** [comment]
The following as after a cold boot of Slide. Opened 2 small threads (less than 100 comments) then opened a massive thread (10k+ comments). You can see the choppiness in opening the comment menu getting worse the further down I am in the post's comments.

https://goo.gl/j65zeQ

**Comment by ccrama** [comment]
Being completely honest, I don't really see the "lag" in the comment menu, I was more imagining a delay in opening or like dropped frames in the menu. What are you noticing when you discuss the lag?

**Comment by Tensounder54** [comment]
In 5.9-alpha2 it lags a little when scrolling at speed but is otherwise fine.

This issue is resolved in a later version of Slide and needs to be closed.

**Comment by timawesomeness** [comment]
#2960 will help with this when lots of comments are collapsed, but doesn't fix the issue. 

To echo what I said there, the main part of the issue is with setTextHtml/getBlocks getting called every time CommentAdapter's onBindViewHolder is called.

**Comment by Tensounder54** [comment]
This issue has been resolved and needs to be closed.
