### ISSUE TITLE
Frontpage shows "Error loading content" after viewing every couple posts

### ISSUE THREAD

**Issue by sagev9000** [ccrama/Slide#2813]
Slide version: 5.8.7
Android version: 8.1

Every so often, when swiping back to the front page from a post, "Error loading content" shows up and I lose my place, having to refresh. It's probably around once every 10 minutes I'm browsing that it happens, which makes it hard to use the app for extended periods.

**Comment by Tensounder54** [comment]
This issue is resolved in a later version of Slide and needs to be closed.

**Comment by sagev9000** [comment]
Still happens occasionally on 5.9-alpha2. Though I'm on Android 9, now.

**Comment by tgp1994** [comment]
Reddit is having some service issues today, so I've been seeing this error a lot, and losing my place. Definitely still producable. Slide 6.2.2, Android 9.
