### ISSUE TITLE
Huge problems with coloring on KitKat

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#361]
On KitKat, there's white outlines on cards.

When the cards are colored, they look awful because there's weird white outlines on the edges.

**Comment by ccrama** [comment]
I'm using MaterialDialogs for all of those :(. Maybe I'm doing something wrong @afollestad?

**Comment by alexsmithfanning** [comment]
The upvote and downvote arrows are also colored incorrectly.

For example, I have /r/EarthPorn set to brown and they buttons are gray. So it makes them hard to see.

**Comment by alexsmithfanning** [comment]
MaterialDialogs for cards? That doesn't make any sense, his library is for dialogs, right?

**Comment by ccrama** [comment]
Oh I thought you said dialogs. Whoops. And cards look totally fine on my N5 running 4.2.2. You sure it isn't something device specific?

**Comment by alexsmithfanning** [comment]
Here's an example of this: https://goo.gl/4Z1cZd

Dialogs have a somewhat similar issue too though. Here's an example of that: https://goo.gl/Udicla

There's outlines on them both, but they are different.

**Comment by afollestad** [comment]
@alexsmithfanning @ccrama well the dialog issue isn't related to Material Dialogs, neither is the card shadow issue. I ran one of the apps I develop for my employer on a KitKat emulator. This is what CardView and MaterialDialogs look like on KitKat:

![kitkat_md](https://cloud.githubusercontent.com/assets/1820165/10949614/8663a346-82f9-11e5-9469-84706a31e4f2.jpeg)

**Comment by ccrama** [comment]
@afollestad Huh, strange. I'm using the AlertDialog.Wrapper, could that cause some sort of compatibility issue? I could try converting them to basic MaterialDialogs if that is the case. Might also be a theme issue so looking into that!

**Comment by afollestad** [comment]
@ccrama no, it shouldn't, AlertDialog.Wrapper is indirectly using `MaterialDialog.Builder` (thus why it's called 'Wrapper' 😉)

**Comment by afollestad** [comment]
I'm guessing there's something in your styles.xml theme that's interfering with the UI

**Comment by ccrama** [comment]
Damn, yeah must be. Will look into it @afollestad ! Thanks for the help :)

@alexsmithfanning  does the outline issue happen on dark theme as well?

**Comment by alexsmithfanning** [comment]
Yes, but its invisible. Because it's well, the dark theme.

**Comment by l3d00m** [comment]
is this fixed with 4.5.0 @alexsmithfanning ?

**Comment by alexsmithfanning** [comment]
Nope. White theme still has black tab text. Sidebar button text is still incorrect.

**Comment by ccrama** [comment]
I'm in the process of making all text that's on a colored back white. Will resolve this issue

**Comment by afollestad** [comment]
My app-theme-engine library might help you.

**Comment by ccrama** [comment]
@afollestad  I looked into it but it would be too much work to re-write Slide to use the engine. I basically coded my own version of it (saves the colors to shared preference, applied onCreate to the views), but the cool thing about ATE is you do casting in order to tint with compatibility. I am just bypassing the whole tinting thing by making it white and removing colors that don't contrast enough with white. I am using ATE for Spiral, though :D

**Comment by ccrama** [comment]
This has all been done for v4.5.1
