### ISSUE TITLE
Freeze on pressing some links

### ISSUE THREAD

**Issue by SZE2** [ccrama/Slide#992]
<githubroot><githubroot><githubroot><br />4.6 alpha issue<br /><br />I found a comment where the freeze is reproducible: https://reddit.com/r/churning/comments/45h3hd/chase_card_ranking_with_524_rule_coming_to_all/czxxkxe?context=3<br /><br />Screencaps: https://vid.me/A06e</githubroot></githubroot></githubroot>

**Comment by Alexendoo** [comment]
```
FATAL EXCEPTION: main
Process: me.ccrama.redditslide, PID: 23887
java.lang.NullPointerException: Attempt to read from field 'java.util.ArrayList me.ccrama.redditslide.OfflineSubreddit.submissions' on a null object reference
    at me.ccrama.redditslide.Fragments.CommentPage.onCreateView(CommentPage.java:338)
    at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
    at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
    at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:163)
    at android.support.v4.view.ViewPager.populate(ViewPager.java:1106)
    at android.support.v4.view.ViewPager.populate(ViewPager.java:952)
    at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1474)
    at android.view.View.measure(View.java:17547)
    at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:727)
    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:463)
    at android.view.View.measure(View.java:17547)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
    at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
    at android.view.View.measure(View.java:17547)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
    at android.view.View.measure(View.java:17547)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
    at android.view.View.measure(View.java:17547)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
    at android.view.View.measure(View.java:17547)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
    at android.view.View.measure(View.java:17547)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2615)
    at android.view.View.measure(View.java:17547)
    at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2015)
    at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1173)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1379)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
    at android.view.Choreographer.doCallbacks(Choreographer.java:580)
    at android.view.Choreographer.doFrame(Choreographer.java:550)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5254)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:
```

**Comment by SZE2** [comment]
Funny, when I follow the permalink it crashes, but when loading the full thread and navigating to the comment it freezes

**Comment by ccrama** [comment]
The link in that comment thread has ?ref=search at the end, and Slide is trying to use ref=search as the context, as that is usually where the context goes.

**Comment by ccrama** [comment]
Fixed

**Comment by SZE2** [comment]
Thanks! 
It still happens intermittently on External Gif links, I'll try to find a reproducible one to post here.

**Comment by SZE2** [comment]
Found a gif that freezes for me consistently: https://reddit.com/r/Android/comments/45rs9y/awsms_has_released_into_public_beta/czzstse?context=3

Screencaps: https://vid.me/czEX

**Comment by SZE2** [comment]
Version 4.6.0-11 5aebd9e

**Comment by ccrama** [comment]
Fixed with my last commit
